name: Move Assigned Issue

on:
  issues:
    types: [assigned, unassigned]

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Move issue on assign
        uses: immitsu/move-issue-on-assign@v2
        with:
          token: ${{ secrets.PROJECTS_MOVE }}
          project: 1
          move-to: "In Progress"
